// <auto-generated />
namespace SchoolBoard.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class _427 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_427));
        
        string IMigrationMetadata.Id
        {
            get { return "202104271759565_427"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
